name: OBS Studio FULL Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 18 * * 6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        sudo apt update && sudo apt install desktop-file-utils
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
        wget https://raw.githubusercontent.com/ivan-hc/OBS-Studio-appimage/main/obs-full-junest.sh
        chmod a+x ./obs-full-junest.sh
        ./obs-full-junest.sh
        mkdir dist
        mv *AppImage* dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: OBS-Studio-FULL-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.8
          with:
            name: OBS-Studio-FULL-x86_64.AppImage

        # Snapshot Release
        - name: get date
          run: |
            SNAPSHOT_TAG="$(date --utc +'%Y%m%d-%H%M%S')"
            echo SNAPSHOT_TAG="${SNAPSHOT_TAG}" >> "${GITHUB_ENV}"
          continue-on-error: false
        - name: create snapshot
          uses: softprops/action-gh-release@v2
          with:
            name: "Snapshot full ${{ env.SNAPSHOT_TAG}}"
            tag_name: "${{ env.SNAPSHOT_TAG}}"
            prerelease: false
            draft: false
            generate_release_notes: false
            make_latest: false
            files: |
              *.AppImage*
          continue-on-error: false

        # Continuous release
        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous-full build
            automatic_release_tag: continuous-full
            prerelease: true
            draft: false
            files: |
              *.AppImage*
            repo_token: ${{ secrets.GITHUB_TOKEN }}
